name: Java lint
on: push
jobs:
    checkstyle-java:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'
            - name: check java installation and version
              run:  |
                    java --version
                    echo "JAVA_HOME is $JAVA_HOME"
            - name: navigate to project folder and run the google checks linter
              run:  |
                    wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar -O checkstyle.jar
                    wget https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.12.4/src/main/resources/google_checks.xml -O google_checks.xml
                    java -jar checkstyle.jar -c google_checks.xml -f plain -o checkstyle-report.txt ./java-project/src
                    cat checkstyle-report.txt
    run-tests:
        runs-on: ubuntu-latest
        needs: checkstyle-java
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'
            - name: check maven installation
              run: |
                   mvn -v
            - name: run maven build and tests
              run: |
                   cd java-project
                   mvn test
    compile-project:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
          - name: checkout repo
            uses: actions/checkout@v4
          - name: setup java
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: '21'
          - name: install maven dependencies
            run:  |
                  cd java-project
                  mvn clean install -DskipTests
          - name: compile project
            run:  |
                  cd java-project
                  mkdir out
                  javac -d out ./src/main/java/Hello.java
          - name: Run main class
            run:  |
                  cd java-project
                  java -cp out Hello
        
