name: Testing passing data between jobs
on: [push]
jobs:
    job1:
       runs-on: ubuntu:latest
       outputs:
        java-ver : ${{ steps.get-version.outputs.version }}
       steps:
        - name: setup java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 21
        - name: get java version
          id:   get-version
          run:  |
                version = $(java -version | head -n 1)
                echo "version=$version" >> $GITHUB_OUTPUT
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: print java version
              run:  |
                    echo "Java version from Job 1: ${{ needs.job1.outputs.java-ver }}"
          
