name: Test Python workflow #name of the workflow
on:
    pull_request:   #event to trigger the workflow
        types:      #filter out the events in which scenarios the workflow needs to be triggered
            - opened
            - assigned
        branches:   #filter the event based on the branch name
            - main
    push: 
        branches:
            - main
        paths-ignore:   #add files to when not to trigger the workflow
            - ./github-actions-exercises/README.md
          
jobs:   #jobs sections which will need to run on workflow
    inital-setup: #job name
        runs-on: ubuntu-latest    #environment to run the job
        steps:    #commands or action to be executed when work job is ran
            - name: check python installation
              run: python --version
            - name: checkout the code
              uses: actions/checkout@v4
            - name: run the github_profile.py file
              run:  |
                    cd ./python-project/github-profile-app
                    python github_profile.py
    run-tests: 
        runs-on: ubuntu-latest
        needs:  inital-setup
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: install requirements
              run:  |
                    cd ./python-project/github-profile-app
                    pip install -r requirements.txt
            - name: run tests
              run:  |
                    cd ./python-project/github-profile-app
                    pytest > pytest-report.txt
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: pytest-report
                path: ./python-project/github-profile-app/pytest-report.txt
    run-linter:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: install requirements
              run:  |
                    cd ./python-project/github-profile-app
                    pip install -r requirements.txt
            - name: run the ruff linter
              run: |
                   cd ./python-project/github-profile-app
                   ruff check
