name: Test Python workflow
on:
    pull_request:
        types:
            - opened
            - assigned
        branches:
            - main
jobs:
    inital-setup:
        runs-on: ubuntu-latest
        steps:
            - name: check python installation
              run: python --version
            - name: checkout the code
              uses: actions/checkout@v4
            - name: run the github_profile.py file
              run:  |
                    cd ./python-project/github-profile-app
                    python github_profile.py
    run-tests:
        runs-on: ubuntu-latest
        needs:  inital-setup
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: install requirements
              run:  |
                    cd ./python-project/github-profile-app
                    pip install -r requirements.txt
            - name: run tests
              run:  |
                    cd ./python-project/github-profile-app
                    pytest
    run-linter:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: install requirements
              run:  |
                    cd ./python-project/github-profile-app
                    pip install -r requirements.txt
            - name: run the ruff linter
              run: |
                   cd ./python-project/github-profile-app
                   ruff check
